export const books = [
  {
    name: 'YOU v/s YOU',
    short_description: 'A 100-Day Personal Transformation Challenge',
    description: 'A powerful 100-day system designed to help you break old patterns, build discipline, and transform your thinking through daily action.',
    image_homepage: '/you vs you F.png',
    image_product_page: '/you vs you B.png',
    category: 'book',
    is_featured: false,
    slug: 'you-vs-you',
  },
  {
    name: 'STUDENTING & PARENTING',
    short_description: 'Build a Positive, Happy Home Culture',
    description: 'A practical guide for students and parents to improve communication, reduce stress, and create a growth-focused environment at home.',
    image_homepage: '/Studenting & Parenting F.png',
    image_product_page: '/Studenting & Parenting B.png',
    category: 'book',
    is_featured: false,
    slug: 'studenting-and-parenting',
  },
  {
    name: 'UNTOLD STORIES OF YOUR HEROES',
    short_description: '100 Transformational Journeys to Inspire',
    description: 'A collection of powerful stories that build courage, mindset, and leadership by learning from real-life struggles and success journeys.',
    image_homepage: '/Untold Stories of Your HEroes F.png',
    image_product_page: '/Untold Stories of Your HEroes B.png',
    category: 'book',
    is_featured: true,
    slug: 'untold-stories-of-your-heroes',
  },
  {
    name: 'SMART STUDIES',
    short_description: 'Study Smarter. Perform Better.',
    description: 'A practical system designed to help students improve focus, retention, and study efficiency using smarter learning techniques.',
    image_homepage: '/Smart Studies F.jpeg',
    image_product_page: '/Smart Studies B.jpeg',
    category: 'book',
    is_featured: false,
    is_active: false,
    slug: 'smart-studies',
  },
  {
    name: 'BUSINESS GROWTH',
    short_description: 'Build, Scale, and Lead with Clarity',
    description: 'A results-driven guide for entrepreneurs and professionals to grow their business, improve decision-making, and create sustainable success.',
    image_homepage: 'https://placehold.co/600x800/0a0a0a/f26522?text=BUSINESS+GROWTH',
    category: 'book',
    is_featured: false,
    slug: 'business-growth',
  },
  {
    name: 'YOUTH',
    short_description: 'Direction, Discipline, and Drive',
    description: 'A powerful guide for young individuals to gain clarity, build discipline, and take control of their future with confidence.',
    image_homepage: 'https://placehold.co/600x800/0a0a0a/f26522?text=YOUTH',
    category: 'book',
    is_featured: false,
    slug: 'youth',
  },
  {
    name: 'LIFE NOTES',
    short_description: 'Simple Thoughts. Powerful Impact.',
    description: 'A collection of deep reflections and practical insights to help you think clearly, stay grounded, and grow consistently in everyday life.',
    image_homepage: '/Life Notes F.png',
    image_product_page: '/Life Notes B.png',
    category: 'book',
    is_featured: false,
    slug: 'life-notes',
  },
];

export const courses = [
  {
    name: 'PARENTING PROGRAM',
    short_description: 'Build a Strong, Positive Home Environment',
    description: 'A practical system to help parents understand their child better, improve communication, and create a growth-driven, stress-free home culture.',
    image_homepage: 'https://placehold.co/800x600/0a0a0a/3b82f6?text=PARENTING+PROGRAM',
    category: 'course',
    price: 999,
    slug: 'parenting-program',
  },
  {
    name: 'MEMORY PROGRAM',
    short_description: 'Unlock Your Brain’s True Potential',
    description: 'Learn proven techniques to improve memory, focus, and retention—so you can learn faster and perform better in academics and life.',
    image_homepage: 'https://placehold.co/800x600/0a0a0a/3b82f6?text=MEMORY+PROGRAM',
    category: 'course',
    price: 1499,
    slug: 'memory-program',
  },
  {
    name: 'TRAIN THE TRAINER',
    short_description: 'Become a Powerful Speaker & Influencer',
    description: 'A structured program to help you develop communication skills, stage confidence, and the ability to impact and influence others.',
    image_homepage: 'https://placehold.co/800x600/0a0a0a/3b82f6?text=TRAIN+THE+TRAINER',
    category: 'course',
    is_active: false,
    price: 4999,
    slug: 'train-the-trainer',
  },
];

export const merchandise = [
  {
    name: 'T-SHIRTS',
    short_description: 'Wear Your Ambition.',
    description: 'This is not just a T-shirt.\nIt\'s a statement that says you refuse to settle for average.\nDesigned for dreamers, achievers, leaders, and changemakers, every time you wear it, you\'re reminded of your commitment to growth, discipline, and excellence.\nDon\'t just wear a brand. Wear a mindset.',
    image_homepage: '/MERCHANDISE/T-Shirt.jpeg',
    category: 'merchandise',
    price: 499,
    slug: 't-shirts',
  },
  {
    name: 'BOTTLES',
    short_description: 'Fuel Your Dreams.',
    description: 'Every goal requires energy. Every achievement starts with discipline.\nStay hydrated, stay focused, and stay committed to becoming the best version of yourself. Whether you\'re studying, working, training, or building your future, this bottle keeps your mission moving forward.\nSuccess flows through daily habits.',
    image_homepage: '/MERCHANDISE/Bottle.png',
    category: 'merchandise',
    price: 399,
    slug: 'bottles',
  },
  {
    name: 'BANDS',
    short_description: 'Small Band. Powerful Reminder.',
    description: 'There will be days when motivation fades.\nThat\'s when commitment matters.\nThis wrist band is your daily reminder that champions don\'t quit when things get difficult—they grow stronger.\nWear determination. Carry confidence.',
    image_homepage: '/MERCHANDISE/Bands.png',
    category: 'merchandise',
    price: 99,
    slug: 'bands',
  },
  {
    name: 'EXAM PADS',
    short_description: 'Write Your Success Story.',
    description: 'Every topper starts with a blank page.\nEvery achievement begins with one answer, one idea, one effort at a time.\nDesigned for focused learners, this exam pad helps you prepare with confidence and perform at your best.\nBecause your future deserves your best effort.',
    category: 'merchandise',
    price: 199,
    slug: 'exam-pads',
  },
  {
    name: 'KEY CHAINS (I-G Series)',
    short_description: 'Carry Your Purpose Everywhere.',
    description: 'Your keys open doors.\nYour mindset opens opportunities.\nThis key chain is a symbol of growth, courage, and the commitment to keep moving forward no matter what challenges come your way.\nKeep your dreams within reach.',
    image_homepage: '/MERCHANDISE/Key-chains.png',
    category: 'merchandise',
    price: 149,
    slug: 'key-chains',
  },
  {
    name: '12-IN-1 PRODUCTIVITY KIT',
    short_description: 'The Success Starter Pack.',
    description: 'What separates successful people from everyone else?\nNot talent.\nNot luck.\nDaily habits.\nThe Productivity Kit is designed to help you plan smarter, focus better, and execute consistently. Every item inside is a step toward higher performance and greater achievement.\nOrganize your day. Transform your life.',
    category: 'merchandise',
    price: 1999,
    slug: 'productivity-kit',
  },
  {
    name: 'PLANTABLE PENCILS',
    short_description: 'Learn. Grow. Give Back.',
    description: 'Knowledge has the power to change lives.\nAnd now, it can help grow life too.\nOnce your pencil journey ends, plant it and watch it transform into a living plant—a beautiful reminder that every lesson learned can create something meaningful.\nPlant knowledge. Grow a better future.',
    category: 'merchandise',
    price: 149,
    slug: 'plantable-pencils',
  },
  {
    name: 'CAP',
    short_description: 'Wear Confidence.',
    description: 'A cap doesn\'t change who you are.\nBut it can remind you who you\'re becoming.\nDesigned for leaders, achievers, and individuals who think beyond limits, this cap represents confidence, courage, and a growth mindset.\nLead with your head held high.',
    image_homepage: '/MERCHANDISE/cap.png',
    category: 'merchandise',
    price: 299,
    slug: 'cap',
  },
  {
    name: 'PENS',
    short_description: 'Where Dreams Meet Action.',
    description: 'Ideas are powerful.\nBut only when they\'re written down and acted upon.\nWhether you\'re setting goals, creating plans, or capturing your next big breakthrough, this pen is designed for people who believe that action creates results.\nYour next success story starts with one line.',
    category: 'merchandise',
    price: 49,
    slug: 'pens',
  },
  {
    name: 'MUGS',
    short_description: 'Sip Motivation Every Day.',
    description: 'Every morning is a new opportunity.\nA new beginning.\nA new chance to become better than yesterday.\nEnjoy your favorite beverage while fueling your mind with positivity, gratitude, and purpose.\nStart your day inspired. End it accomplished.',
    image_homepage: '/MERCHANDISE/Mugs.jpeg',
    category: 'merchandise',
    price: 349,
    slug: 'mugs',
  },
  {
    name: 'CANDLES',
    short_description: 'Light Up Your Potential.',
    description: 'Great ideas are born in moments of calmness and clarity.\nCreate an environment that inspires focus, reflection, creativity, and inner peace. Perfect for studying, planning, journaling, meditation, or simply recharging your mind.\nSometimes the brightest breakthroughs begin with a single flame.',
    image_homepage: '/MERCHANDISE/Candels.jpeg',
    category: 'merchandise',
    price: 399,
    slug: 'candles',
  },
];
